---
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: quay.io/pkumari/demo-app-test
    newName: quay.io/pkumari/demo-app-test
    newTag: latest

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
