---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-application-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-test
    server: https://kubernetes.default.svc
  source:
    path: demo/manifest
    repoURL: https://github.com/prietyc123/demo-app.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
